name: healtho_gym
description: "A new Flutter project."

publish_to: "none" # Prevent accidental publication to pub.dev.

version: 1.0.0+1

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.2.5
  path: ^1.8.3
  cupertino_icons: ^1.0.2
  otp_text_field_v2: ^1.0.3
  otp_timer_button: ^1.1.1
  flutter_rating_bar: ^4.0.1
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  # Add your assets.
  assets:
    - assets/img/

  # Add custom fonts.
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/font/Poppins-Regular.ttf
        - asset: assets/font/Poppins-Medium.ttf
          weight: 500
        - asset: assets/font/Poppins-Light.ttf
          weight: 300
        - asset: assets/font/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/font/Poppins-Bold.ttf
          weight: 700
